project:
  title: "Slides"

editor: visual

format:
  revealjs:
     html-math-method: mathjax
     theme: slides.scss
     transition: fade
     slide-number: true
     chalkboard: true
     highlight-style: a11y-dark

execute:
  freeze: auto
  echo: true
  warning: true
knitr:
  opts_chunk: 
    R.options:
      width: 90     